---
apiVersion: v1
kind: Secret
metadata:
  name: itmo-ratings-secrets
  namespace: itmo-ratings
type: Opaque
stringData:
  telegram-api-token: "telegram-token"
  program-id: "program_id"
  student-id: "student_id"
  telegram-user-id: "user_id"