---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: time-proxy
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/EgorTarasov/home-lab.git
        targetRevision: HEAD
        path: environments/dev/time
    destination:
        server: https://kubernetes.default.svc
        namespace: time
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
        syncOptions:
            - Validate=true
            - CreateNamespace=true
            - PruneLast=true
