apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-tls
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  commonName: rancher.k3s.larek.tech
  dnsNames:
  - rancher.k3s.larek.tech